# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [4]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')

### Step 4. How many products cost more than $10.00?

In [79]:
chipo.head(1)
chipo['dollar_price'] = [float(val[1:]) for val in chipo['item_price']]

# delete duplicates in item_name, quantity, and choice_description 
chipo_no_dup = chipo.drop_duplicates(['item_name','quantity','choice_description'])

# only get orders with single items
chipo_single_item = chipo_no_dup[chipo_no_dup['quantity'] == 1]

# items_over_10 = [item for item in filter(lambda x : x > 10, chipo_single_item['dollar_price'])]
items_over_10 = chipo_single_item[chipo_single_item['dollar_price'] > 10]
items_over_10 = items_over_10.drop_duplicates('item_name')
print(f"The number of items costing over $10 is {len(items_over_10)}")
items_over_10

The number of items costing over $10 is 25

,order_id,quantity,item_name,choice_description,item_price,dollar_price
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98,10.98
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75,11.75
57,26,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25,11.25
62,28,1,Veggie Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25
79,35,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Cheese, Lett...",$11.25,11.25
90,40,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.75,11.75
93,41,1,Carnitas Burrito,"[Roasted Chili Corn Salsa, [Sour Cream, Guacam...",$11.75,11.75
97,43,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.75,11.75
130,57,1,Barbacoa Burrito,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",$11.75,11.75
168,75,1,Barbacoa Crispy Tacos,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.75,11.75
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25
250,109,1,Chicken Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$10.98,10.98
365,158,1,Chicken Crispy Tacos,"[Tomatillo Green Chili Salsa, [Black Beans, Ch...",$11.25,11.25
606,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Cheese, Gua...",$11.89,11.89
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25,11.25
988,406,1,Barbacoa Soft Tacos,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",$11.75,11.75
1008,413,1,Carnitas Crispy Tacos,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$11.75,11.75
1132,468,1,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.89,11.89
1189,488,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25
1229,501,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",$11.89,11.89
1353,552,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$11.75,11.75
1963,793,1,Carnitas Soft Tacos,"[Fresh Tomato Salsa, [Sour Cream, Guacamole]]",$11.75,11.75
2231,899,1,Steak Crispy Tacos,"[Fresh Tomato Salsa, Guacamole]",$11.75,11.75

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [85]:
item_df = chipo_single_item[['item_name','item_price']].drop_duplicates('item_name')
item_df

                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39
1                                      Izze     $3.39
2                          Nantucket Nectar     $3.39
3     Chips and Tomatillo-Green Chili Salsa     $2.39
5                              Chicken Bowl    $10.98
6                             Side of Chips     $1.69
7                             Steak Burrito    $11.75
8                          Steak Soft Tacos     $9.25
10                      Chips and Guacamole     $4.45
11                     Chicken Crispy Tacos     $8.75
12                       Chicken Soft Tacos     $8.75
16                          Chicken Burrito     $8.49
21                         Barbacoa Burrito     $8.99
27                         Carnitas Burrito     $8.99
28                              Canned Soda     $1.09
33                            Carnitas Bowl     $8.99
34                            Bottled Water     $1.09
38    Chips and Tomatillo Green Chili Salsa     $2.95
39                            Barbacoa Bowl    $11.75
40                                    Chips     $2.15
44                       Chicken Salad Bowl     $8.75
54                               Steak Bowl     $8.99
56                      Barbacoa Soft Tacos     $9.25
57                           Veggie Burrito    $11.25
62                              Veggie Bowl    $11.25
92                       Steak Crispy Tacos     $9.25
111     Chips and Tomatillo Red Chili Salsa     $2.95
168                   Barbacoa Crispy Tacos    $11.75
186                       Veggie Salad Bowl    $11.25
191      Chips and Roasted Chili-Corn Salsa     $2.39
233      Chips and Roasted Chili Corn Salsa     $2.95
237                     Carnitas Soft Tacos     $9.25
250                           Chicken Salad    $10.98
263                       Canned Soft Drink     $1.25
298                       6 Pack Soft Drink     $6.49
300     Chips and Tomatillo-Red Chili Salsa     $2.39
510                                 Burrito     $7.40
520                            Crispy Tacos     $7.40
554                   Carnitas Crispy Tacos     $9.25
606                        Steak Salad Bowl    $11.89
664                             Steak Salad     $8.99
673                                    Bowl     $7.40
674       Chips and Mild Fresh Tomato Salsa     $3.00
738                       Veggie Soft Tacos    $11.25
1132                    Carnitas Salad Bowl    $11.89
1229                    Barbacoa Salad Bowl    $11.89
1414                                  Salad     $7.40
1653                    Veggie Crispy Tacos     $8.49
1694                           Veggie Salad     $8.49
3750                         Carnitas Salad     $8.99

### Step 6. Sort by the name of the item

In [87]:
item_df.sort_values('item_name')

                                  item_name item_price
298                       6 Pack Soft Drink     $6.49
39                            Barbacoa Bowl    $11.75
21                         Barbacoa Burrito     $8.99
168                   Barbacoa Crispy Tacos    $11.75
1229                    Barbacoa Salad Bowl    $11.89
56                      Barbacoa Soft Tacos     $9.25
34                            Bottled Water     $1.09
673                                    Bowl     $7.40
510                                 Burrito     $7.40
28                              Canned Soda     $1.09
263                       Canned Soft Drink     $1.25
33                            Carnitas Bowl     $8.99
27                         Carnitas Burrito     $8.99
554                   Carnitas Crispy Tacos     $9.25
3750                         Carnitas Salad     $8.99
1132                    Carnitas Salad Bowl    $11.89
237                     Carnitas Soft Tacos     $9.25
5                              Chicken Bowl    $10.98
16                          Chicken Burrito     $8.49
11                     Chicken Crispy Tacos     $8.75
250                           Chicken Salad    $10.98
44                       Chicken Salad Bowl     $8.75
12                       Chicken Soft Tacos     $8.75
40                                    Chips     $2.15
0              Chips and Fresh Tomato Salsa     $2.39
10                      Chips and Guacamole     $4.45
674       Chips and Mild Fresh Tomato Salsa     $3.00
233      Chips and Roasted Chili Corn Salsa     $2.95
191      Chips and Roasted Chili-Corn Salsa     $2.39
38    Chips and Tomatillo Green Chili Salsa     $2.95
111     Chips and Tomatillo Red Chili Salsa     $2.95
3     Chips and Tomatillo-Green Chili Salsa     $2.39
300     Chips and Tomatillo-Red Chili Salsa     $2.39
520                            Crispy Tacos     $7.40
1                                      Izze     $3.39
2                          Nantucket Nectar     $3.39
1414                                  Salad     $7.40
6                             Side of Chips     $1.69
54                               Steak Bowl     $8.99
7                             Steak Burrito    $11.75
92                       Steak Crispy Tacos     $9.25
664                             Steak Salad     $8.99
606                        Steak Salad Bowl    $11.89
8                          Steak Soft Tacos     $9.25
62                              Veggie Bowl    $11.25
57                           Veggie Burrito    $11.25
1653                    Veggie Crispy Tacos     $8.49
1694                           Veggie Salad     $8.49
186                       Veggie Salad Bowl    $11.25
738                       Veggie Soft Tacos    $11.25

### Step 7. What was the quantity of the most expensive item ordered?

In [138]:
# Is the question, "How many times was the most expensive item ordered?"
item_df['item_price'] = [float(val) for val in item_df['item_price']]
item_df = item_df.sort_values('item_price', ascending=False)
most_expensive_item = item_df.head(1)['item_name'].array[0]
print(f"The most expensive item is {most_expensive_item}.")
most_exp_df = chipo_no_dup[chipo_no_dup['item_name'] == most_expensive_item]
print(f"This was ordered {most_exp_df['quantity'].sum()} times.")

The most expensive item is Steak Salad Bowl.
This was ordered 30 times.

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [151]:
# this will probably be better with regex
veg_df = chipo[chipo['item_name'] == 'Veggie Salad Bowl']
print(f"This was ordered {veg_df['quantity'].sum()} times.")

This was ordered 18 times.

### Step 9. How many times did someone order more than one Canned Soda?

In [153]:
soda_df = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]
len(soda_df)

20